/**
 * Auto-generated by `supabase gen types` (via the Supabase MCP).
 * Regenerate whenever the schema changes.
 *
 * Source of truth: the Supabase project at bkxfnginzptwthypriub.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: '14.5';
  };
  public: {
    Tables: {
      prices: {
        Row: {
          id: number;
          is_true_special: boolean;
          member_only: boolean;
          price: number;
          product_id: string;
          retailer_code: string;
          retailer_sku: string | null;
          scrape_run_id: number | null;
          scraped_at: string;
          was_price: number | null;
        };
        Insert: {
          id?: number;
          is_true_special?: boolean;
          member_only?: boolean;
          price: number;
          product_id: string;
          retailer_code: string;
          retailer_sku?: string | null;
          scrape_run_id?: number | null;
          scraped_at?: string;
          was_price?: number | null;
        };
        Update: Partial<Database['public']['Tables']['prices']['Insert']>;
        Relationships: [];
      };
      products: {
        Row: {
          aliases: string[];
          brand: string;
          category: string | null;
          created_at: string;
          generic_type: string | null;
          id: string;
          name: string;
          size: string | null;
          updated_at: string;
        };
        Insert: {
          aliases?: string[];
          brand: string;
          category?: string | null;
          created_at?: string;
          generic_type?: string | null;
          id: string;
          name: string;
          size?: string | null;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['products']['Insert']>;
        Relationships: [];
      };
      retailers: {
        Row: {
          catalogue_url: string | null;
          code: string;
          created_at: string;
          derived_from_retailer: string | null;
          derived_markup: number | null;
          display_name: string;
          is_active: boolean;
          kind: string;
          scraping_strategy: string;
        };
        Insert: {
          catalogue_url?: string | null;
          code: string;
          created_at?: string;
          derived_from_retailer?: string | null;
          derived_markup?: number | null;
          display_name: string;
          is_active?: boolean;
          kind: string;
          scraping_strategy?: string;
        };
        Update: Partial<Database['public']['Tables']['retailers']['Insert']>;
        Relationships: [];
      };
      scrape_runs: {
        Row: {
          errors_count: number;
          finished_at: string | null;
          id: number;
          items_emitted: number;
          kind: string;
          notes: string | null;
          ok: boolean | null;
          retailer_code: string;
          source_url: string | null;
          started_at: string;
        };
        Insert: {
          errors_count?: number;
          finished_at?: string | null;
          id?: number;
          items_emitted?: number;
          kind: string;
          notes?: string | null;
          ok?: boolean | null;
          retailer_code: string;
          source_url?: string | null;
          started_at?: string;
        };
        Update: Partial<Database['public']['Tables']['scrape_runs']['Insert']>;
        Relationships: [];
      };
    };
    Views: {
      latest_prices: {
        Row: {
          is_true_special: boolean | null;
          member_only: boolean | null;
          price: number | null;
          product_id: string | null;
          retailer_code: string | null;
          retailer_sku: string | null;
          scrape_run_id: number | null;
          scraped_at: string | null;
          was_price: number | null;
        };
        Relationships: [];
      };
    };
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

export type PriceRow = Database['public']['Tables']['prices']['Row'];
export type PriceInsert = Database['public']['Tables']['prices']['Insert'];
export type LatestPriceRow = Database['public']['Views']['latest_prices']['Row'];
export type ProductRow = Database['public']['Tables']['products']['Row'];
export type RetailerRow = Database['public']['Tables']['retailers']['Row'];
export type ScrapeRunRow = Database['public']['Tables']['scrape_runs']['Row'];
export type ScrapeRunInsert = Database['public']['Tables']['scrape_runs']['Insert'];
